# Generated by Django 5.0.6 on 2024-06-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True)),
                ('english_address', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'ATM Addresses',
                'db_table': 'atm_address',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_town_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=3, null=True)),
                ('town', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=4, null=True)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('density', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'atm_city',
            },
        ),
        migrations.CreateModel(
            name='AtmMain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atm_code', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=10, null=True)),
                ('atm_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('category', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('atm_install', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=200, null=True)),
                ('service_type', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('use_wheel', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
                ('voice', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atm.atmaddress')),
                ('city_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atm.city')),
            ],
            options={
                'verbose_name_plural': 'ATM Main',
                'db_table': 'atm_main',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('payment', 'Payment')], default='', max_length=10)),
                ('atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atm', to='atm.atmmain')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atm.customer')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='atm.customer')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
            },
        ),
    ]
