# Generated by Django 5.0.6 on 2024-06-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0008_transaction_type_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='atm.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='atm.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', '存款'), ('withdraw', '取款'), ('transfer', '轉帳'), ('payment', '支付')], default='', max_length=10),
        ),
    ]
