# Generated by Django 5.0.6 on 2024-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0009_rename_customer_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
