# Generated by Django 5.0.6 on 2024-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0010_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
