# Generated by Django 5.0.6 on 2024-06-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0011_customer_join_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
