# Generated by Django 5.0.6 on 2024-06-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0012_alter_customer_join_time_alter_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
    ]
